grails-app/controllers/canthefason/ContactController.groovy
package canthefason

class ContactController {

    def mailService

    def index() {
        def command = new ContactCommand()
        [command: command, fasonMode: session.getAttribute("fasonMode")]
    }

    def post(ContactCommand command) {

        if (command.validate()) {
            def renderedMail = g.render(template: 'message', model: [command: command])
            mailService.sendMail {
                to 'can.yucel@gmail.com'
                from command.email
                subject 'Mesaj var, bak bi'
                html renderedMail
            }

            flash.message = 'Message successfully sent'
            command = new ContactCommand()
        }

        render view: 'index', model: [command: command]
    }
}

class ContactCommand {
    String fullname
    String email
    String message

    static constraints = {
        fullname blank: false
        email blank: false, email: true
        message blank: false
    }
}

grails-app/controllers/canthefason/IndexController.groovy
package canthefason

import org.apache.commons.lang.StringUtils

class IndexController {

    def index() {
        def mode = request.getParameter("mode")
        def fasonMode = false
        if (mode == "fason") {
            fasonMode = true;
            session.setAttribute('fasonMode', true)
        } else if (mode =="can") {
            fasonMode = false;
            session.setAttribute('fasonMode', false)
        } else if (StringUtils.isBlank(mode)) {
            fasonMode = session.getAttribute('fasonMode') ? session.getAttribute('fasonMode') : false
        }


        [fasonMode: fasonMode, mode: mode]
    }

    def change() {
        session.setAttribute('fasonMode', !session.getAttribute('fasonMode'))
        def mode = session.getAttribute('fasonMode') ? "fason" : "can"
        redirect (action: "index", params: ["mode": mode])
    }

    def topBar() {
        def fasonMode = session.getAttribute('fasonMode') ? session.getAttribute('fasonMode') : false
        [fasonMode: fasonMode]
    }

    def footer() {
        def text = session.getAttribute('fasonMode') ? "Singing & Guitar Playing Muppet" : "Agile Software Developer"
        [text: text]
    }

    def underConst() {
        def fasonMode = session.getAttribute('fasonMode') ? session.getAttribute('fasonMode') : false
        [fasonMode: fasonMode]
    }

    def resume() {
        session.setAttribute('fasonMode', false)
        [fasonMode: false]
    }

}

grails-app/controllers/canthefason/MediaController.groovy
package canthefason

class MediaController {

    def picture() {

        session.setAttribute('fasonMode', true)
        render (view: "index", model: [dataType:'picture', title: 'Gallery', fasonMode: true])
    }

    def performance() {
        session.setAttribute('fasonMode', true)
        render (view: "index", model: [dataType:'performance', title: 'Performance', fasonMode: true])
    }


}

grails-app/views/contact/_message.gsp
<div>From: ${command.fullname} - ${command.email}</div>
<div>Message: ${command.message}</div>

grails-app/views/contact/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:render template="../index/title"/>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-35926990-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>

%{--<iframe class="hidden-phone" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/?ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=40.052282,86.572266&amp;t=m&amp;z=4&amp;output=embed"></iframe>--}%
<iframe class="hidden-phone" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Cafera%C4%9Fa+Mh.,+Istanbul,+Turkey&amp;aq=&amp;sll=40.992696,29.001287&amp;sspn=0.037705,0.090723&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Cafera%C4%9Fa+Mh.,+Kad%C4%B1k%C3%B6y%2FIstanbul+Province,+Turkey&amp;z=14&amp;iwloc=A&amp;ll=40.985121,29.02488&amp;output=embed"></iframe>

<div class="container">

    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span4 contact-info">
                    <div class="page-header">
                        <h2>Contact me</h2>
                        <p></p>
                    </div>
                    <h4>Social Connection</h4>
                    <div class="member-social">
                        <a href="<g:message code="contact.facebook"/>">
                            <i class="elegant-icon-facebook"></i>
                        </a>
                        <a href="<g:message code="contact.linkedin"/>">
                            <i class="elegant-icon-linkedin"></i>
                        </a>
                        <a href="<g:message code="contact.twitter"/>">
                            <i class="elegant-icon-twitter"></i>
                        </a>
                        <a href="<g:message code="contact.instagram"/>">
                            <i class="elegant-icon-instagram"></i>
                        </a>
                        <a href="<g:message code="contact.youtube"/>">
                            <i class="elegant-icon-youtube"></i>
                        </a>
                        <a href="<g:message code="contact.myspace"/>">
                            <i class="elegant-icon-myspace"></i>
                        </a>
                    </div>
                    <hr>
                    <h4>Contact via email</h4>
                    <p><a href="mailto:can.yucel@gmail.com"><i class="icon-envelope"></i> can.yucel@gmail.com</a></p>
                    <hr>
                    <h4>Call me</h4>
                    <p>+90 (530) 419 84 82</p>
                </div>
                <div class="span8">
                    <div class="page-header center">
                        <h2>Contact form</h2>
                        <p></p>
                        <p></p>
                    </div>
                    <g:form action="post" controller="contact"  class="">
                        <label for="fullname"><p>Your name</p></label>
                        <input type="text" name="fullname" id="fullname" value="${command?.fullname}">
                        <g:eachError var="err" bean="${command}" field="fullname">
                            <span class="text-error"><g:message error="${err}" /></span>
                        </g:eachError>
                        <label for="email"><p>Your email</p></label>
                        <input type="text" id="email" name="email" value="${command?.email}">
                        <g:eachError var="err" bean="${command}" field="email">
                            <span class="text-error"><g:message error="${err}" /></span>
                        </g:eachError>
                        <label for="message"><p>Your message</p></label>
                        <textarea name="message" id="message" cols="30" rows="10" class="span4" placeholder="Type here..." value="${command?.message}"></textarea>
                        <g:eachError var="err" bean="${command}" field="message">
                            <span class="text-error"><g:message error="${err}" /></span>
                        </g:eachError>
                        <br>
                        <button type="submit" class="btn btn-success">Send</button>
                        <g:if test="${flash.message}">
                            <span class='text-success'>*${flash.message}</span>
                        </g:if>
                    </g:form>
                </div>
            </div>
        </div>
    </div>

</div>


</body>
</html>

grails-app/views/index/_index-can.gsp
<div class="slider-block" xmlns="http://www.w3.org/1999/html">

    <div id="myCarousel" class="carousel slide">
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item">
                <img src="${resource(dir: 'images', file: 'slide_bg2.jpeg')}" alt="Someimage">
                <div class="caption bottom-left container">
                    <p class="medium white text-pink">Agile Software Developer</p>
                </div>
            </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>

</div>

<div class="hero-unit">
    <div class="container">
        <div class="row">
            <div class="span12">
                <h1>In development we <strong class="pink">trust</strong></h1>
            </div>
        </div>
    </div>
</div>

<div class="container">

    <!-- TESTIMONIALS 3col -->
    <div class="row testimonials">
        <div class="span4">
            <img class="border" src="${resource(dir: 'images', file: 'n11-logolu.png')}" alt="Numara 11">
            <a href="http://www.n11.com" target="_blank"> <h2>Numara 11</h2></a>
            <p>B2C E-Commerce project. <br/>(Financed by Dogus Planet)</p>
        </div>
        <div class="span4">
            <img src="${resource(dir: 'images', file: 'playstore.png')}" alt="Playstore">
            <a href="http://www.playstore.com" target="_blank"> <h2>Playstore</h2></a>
            <p>Steam like gaming store. <br/> (Financed by TTnet Inc.)</p>
            %{--<p>Backend software design and implementation of TTnet Inc. gaming store</p>--}%
        </div>
        <div class="span4">
            <img src="${resource(dir: 'images', file: 'denizalti.png')}" alt="Datas">
            <h2>DATAS</h2>
            <p>Submarine Tactics Simulator. <br/>(Financed by Turkish Naval Forces)</p>
        </div>
    </div>

    <div class="section-title">
        <h2>Some other projects still in progress/already finished. </h2>
    </div>

    <!-- TESTIMONIALS 4col -->
    <div class="row testimonials">
        <div class="span3">
            <img class="border" src="${resource(dir: 'images', file: 'guzel-insan.png')}" alt="Guzel Insan">
            <h2>Guzel Insan</h2>
            <p>Social scholarship platform. </p>
        </div>
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'modakeyfi.png')}" alt="Keyfimoda / Modajenik">
            <h2>Keyfimoda / Modajenik</h2>
            %{--<p>Third party integration via SOAP web services</p>--}%
            <p>Private shopping platforms.</p>
        </div>
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'turkcell-goller-cepte.png')}" alt="Goller Cepte">
            <h2>Goller Cepte</h2>
            %{--<p>Frontend-Backend integration of Turkcell service.</p>--}%
            <p>Turkcell wap service.</p>
        </div>
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'tuttur-logo.png')}" alt="Tuttur">
            <h2>Tuttur.com</h2>
            <p>Online betting system.</p>
        </div>
    </div>
</div><!-- .container -->

grails-app/views/index/_index-fason.gsp
<div class="slider-block">

    <div id="myCarousel" class="carousel slide">
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item">
                <img src="${resource(dir: 'images', file: 'mayhem.jpeg')}" alt="Someimage">
                <div class="caption bottom-left container">

                    <p class="medium white text-pink">Singer & Guitar Player</p>
                </div>
            </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>

</div>

<div class="hero-unit">
    <div class="container">
        <div class="row">
            <div class="span12">
                <h1>In Music we <strong class="pink">trust</strong></h1>
            </div>
        </div>
    </div>
</div>

<div class="container">

    <!-- TESTIMONIALS 3col -->
    <div class="row-fluid testimonials">
        <div class="span3"></div>
        <div class="span6">
            <a href="http://www.facebook.com/cipetpetband" target="_blank">
                <img src="${resource(dir: 'images', file: 'cipetpet.png')}" alt="Çipetpet Indie Rock"/>
                <h1>Çipetpet</h1>
            </a>
        </div>
        <div class="span3"></div>
    </div>
    <div class="row testimonials">

        <div class="span4">
            <a href="http://www.facebook.com/NeseliGunlerKumpanyasi" target="_blank">
                <img src="${resource(dir: 'images', file: 'neseli.png')}" alt="Neşeli Günler Turkish Pop"/>
                <h2>Neşeli Günler Kumpanyası</h2>
            </a>
        </div>
        <div class="span4">
            <a href="http://www.facebook.com/pages/Müzikus-Çok-Sesli-Pop-ve-Rock-KoroSU/121372344550221">
                <img src="${resource(dir: 'images', file: 'korosu.png')}" alt="Sabanci University Pop & Rock Choir"/>
                <h2>Sabancı University Pop &amp Rock Choir</h2>
            </a>
        </div>
        <div class="span4">
            <a href="http://www.facebook.com/pages/Shuffle/167540263993" target="_blank">
                <img src="${resource(dir: 'images', file: 'shuffle.png')}" alt="Shuffle Alternative Pop/Rock"/>
                <h2>Shuffle</h2>
            </a>
        </div>


    </div>


    <div class="section-title">
        <h2>Also known as</h2>
    </div>

    <!-- TESTIMONIALS 4col -->
    <div class="row testimonials">
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'kermit_bey.png')}" title="Kermit the Frog" alt="Kermit the Frog">
        </div>
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'frodo_bey.png')}" title="Frodo the Ring Bearer">
        </div>
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'kirpik_bey.png')}" title="Oscar the Grouch">
        </div>
        <div class="span3">
            <img src="${resource(dir: 'images', file: 'krtek_bey.png')}" title="Krtek the Mole">
        </div>
    </div>
</div><!-- .container -->

%{--<div class="hero-unit">--}%
%{--<div class="container">--}%
%{--<div class="row">--}%
%{--<div class="span12">--}%
%{--<h1>Who are we?</h1>--}%
%{--</div>--}%
%{--</div>--}%
%{--</div>--}%
%{--</div>--}%

%{--<div class="container">--}%
%{--<div class="team">--}%

%{--<div class="row">--}%

%{--<div class="span4 section-title horizontal-left">--}%
%{--<h2>Team members <i class="icon-chevron-right"></i></h2>--}%
%{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod--}%
%{--tempor incididunt ut labore et dolore magna aliqua.--}%
%{--<div class="btn btn-large pull-right">Know more &raquo;</div></p>--}%
%{--</div>--}%

%{--<div class="span8">--}%
%{--<div class="row">--}%
%{--<div class="span2 item">--}%
%{--<div class="circle-thumbnail">--}%
%{--<img src="${resource(dir: 'images', file: '1.jpeg')}" alt="team member">--}%
%{--</div>--}%
%{--<h2>Kathy Jackson</h2>--}%
%{--<p>Incididunt ut labore et dolore magna aliqua.</p>--}%
%{--</div>--}%
%{--<div class="span2 item">--}%
%{--<div class="circle-thumbnail">--}%
%{--<img src="${resource(dir: 'images', file: '2.jpeg')}" alt="team member">--}%
%{--</div>--}%
%{--<h2>Erin Fields</h2>--}%
%{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod--}%
%{--tempor. </p>--}%
%{--</div>--}%
%{--<div class="span2 item">--}%
%{--<div class="circle-thumbnail">--}%
%{--<img src="${resource(dir: 'images', file: '3.jpeg')}" alt="team member">--}%
%{--</div>--}%
%{--<h2>Steven Jones</h2>--}%
%{--<p>Ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>--}%
%{--</div>--}%
%{--<div class="span2 item">--}%
%{--<div class="circle-thumbnail">--}%
%{--<img src="${resource(dir: 'images', file: '4.jpeg')}" alt="team member">--}%
%{--</div>--}%
%{--<h2>Jan Kowalski</h2>--}%
%{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>--}%
%{--</div>--}%
%{--</div>--}%
%{--</div>--}%
%{--</div>--}%



%{--</div>--}%
%{--</div> <!-- /container -->--}%

grails-app/views/index/_title.gsp
<g:if test="${!fasonMode}">
    <title>Can Yucel - Agile Software Developer</title>
</g:if>
<g:else>
    <title>Can the Fason - Singer & Guitar Player</title>
</g:else>

grails-app/views/index/footer.gsp
<footer>
    <div class="container">
        <!-- COPYRIGHTS -->
        <p class="pull-left">canthefason.com - ${text}</p>
        <p class="pull-right"><a href="#">Back to top</a></p>
    </div>
</footer>

grails-app/views/index/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>

    <g:render template="title"/>
    <meta name='layout' content='main'/>
    <g:if test="${mode != null}">
        <link rel="canonical" href="${grailsApplication.config.grails.serverURL}/?mode=${mode}" />
    </g:if>
    <g:else>
        <link rel="canonical" href="${grailsApplication.config.grails.serverURL}" />
    </g:else>

    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-35926990-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>
<g:if test="${!fasonMode}">
    <g:render template="index-can"></g:render>
</g:if>
<g:else>
    <g:render template="index-fason"></g:render>
</g:else>

</body>
</html>

grails-app/views/index/resume.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html >

<head>
    <meta name='layout' content='main'/>
    <g:render template="title"/>
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'light.css')}" type="text/css">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'font-awesome.css')}" type="text/css">


</head>
<body>

<div class="container-fluid" style="margin-top: 40px;">
    <div class="row-fluid">
        <div class="profile-block span12">
            <div class="span6 engulf" id="profile">
                <div class="profile-img pull-left">
                    <img src="${resource(dir: "images", file: "can-efendi.png")}" alt="profile picture"/>
                </div>
                <div class="profile-description pull-left">
                    <h1>Can Yücel</h1>
                    <h3>Agile Software Developer</h3>
                    <div class="contact-details">
                        <i class="icon-map-marker"></i> Istanbul, Turkey | MSc Software Engineer <br/>
                        <i class="icon-inbox"> </i> <a href="#contactModel" data-toggle="modal">  <g:message code="contact.email"/></a><br/>
                        <i class="icon-phone-sign"> </i>   <g:message code="contact.phone"/> <br/>
                        <i class="icon-globe"> </i>  <a href="http://www.canthefason.com">www.canthefason.com</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="timeline">
            <div class="experience">
                <div class="heading alert alert-info">
                    <i class=" icon-briefcase"></i> Work experience
                </div>
                <div class="list-block ">
                    <img src="${resource(dir: "images", file: "n11-cv-logo.png")}" class="pull-left" width="100" height="100" alt="company logo" />
                    <span class="bold">February 2013 - March 2013</span>
                    Software Developer at n11.com | Istanbul / TURKEY     <br/>
                    <span class="more-info">
                        <ol>
                            <li></li>
                            <li>
                                <a href="http://www.n11.com">n11.com</a> <br/>
                                Mallfront development (Java, Spring MVC)
                            </li>
                        </ol>
                    </span>
                </div>
                <div class="list-block ">
                    <img src="${resource(dir: "images", file: "granul-cv-logo.png")}" class="pull-left" alt="company logo" />
                    <span class="bold">May 2012  - January 2013</span>
                    Software Developer at Granul Technology | Istanbul / TURKEY     <br/>
                    <span class="more-info">
                        <ol>
                            <li></li>
                            <li>
                                <a href="http://www.n11.com" target="_blank">n11.com</a> <br/> Development of REST Services (JAX-RS) and Search API in mallfront.
                            </li>
                            <li>
                                <a href="http://gollercepte.tv" target="_blank">GollerCepte.tv</a> <br/> FE – BE integration for the smart phone and Ipad environments. (ASP .NET)<br/>
                            </li>
                            <li>
                                <a href="http://www.guzelinsan.org" target="_blank">GuzelInsan.org</a> <br/> Development and system administration of the project. (Grails)
                            </li>
                        </ol>
                    </span>
                </div>
                <div class="list-block ">
                    <img src="${resource(dir: "images", file: "tart-cv-logo.png")}" class="pull-left" alt="company logo"/>
                    <span class="bold">February 2011 - May 2012</span>
                    Lead Backend Developer at Tart New Media | Istanbul / TURKEY <br/>
                    <span class="more-info">
                        <ol>
                            <li></li>
                            <li>
                                <a href="http://www.playstore.com" target="_blank">Playstore.com</a> <br/>
                                Responsible for the architectural design and development. <br/>
                                Build management by Jenkins and Git. <br/>
                                Implementation of indexing mechanism via Apache SOLR. <br/>
                                Development of an SQL generator, based on Doctrine 2.0 entities. (PHP, Zend Framework)
                            </li>
                            <li>
                                <a href="http://www.keyfimoda.com" target="_blank">Keyfimoda.com</a> <br/>
                                Development of SOAP web services. (PHP, Zend Framework)
                            </li>
                        </ol>
                    </span>
                </div>
                <div class="list-block ">
                    <img src="${resource(dir: "images", file: "tubitak-cv-logo.png")}" class="pull-left" alt="company logo" />
                    <span class="bold">October 2009 - January 2011 </span>
                    Frontend Developer at TÜBİTAK | Kocaeli / TURKEY   <br/>
                    <span class="more-info">
                        <ol>
                            <li></li>
                            <li>
                                DATAS (Submarine Tactics Simulator)<br/>
                                Development of graphical user interface and plugins of the project. (C++, Qt)
                            </li>
                        </ol>
                    </span>
                </div>
                <div class="list-block ">
                    <img src="${resource(dir: "images", file: "sabanci-cv-logo.png")}" class="pull-left" alt="company logo" />
                    <span class="bold">September 2007 - June 2009 </span>
                    Teaching Assistant at Sabancı University  | Istanbul / TURKEY <br/>
                    <span class="more-info">
                        <ol>
                            <li></li>
                            <li>Software Engineering (Spring 2009)<br/>
                            Advanced Programming (Spring 2008)<br/>
                            Introduction to Computing (Fall 2007 & Fall 2008)</li>
                        </ol>
                    </span>
                </div>
                <div class="list-block ">
                    <img src="${resource(dir: "images", file: "argefar-cv-logo.png")}" class="pull-left" alt="company logo" />
                    <span class="bold">July 2004 - June 2007</span>
                    Supervisor at Argefar  | Izmir / TURKEY <br/>
                    <span class="more-info">
                        <ol>
                            <li></li>
                            <li>Responsible for the management of the IT department. (Part-time)</li>
                        </ol>
                    </span>
                </div>
            </div>
            <div class="education">
                <div class="heading alert alert-info">
                    <i class=" icon-book"></i> Education
                </div>
                <div class="list-block ">
                    <span class="bold">Sabancı University</span>
                    MS, Computer Science - Computer & Network Security Program<br/>
                    <ol>
                        <li></li>
                        <li>
                            Thesis: A Secure Micropayment Scheme in Wireless Mesh Networks <br/>
                            Advisor: Assoc. Prof. Dr. Albert Levi
                        </li>
                    </ol>
                    2007 -  2010
                </div>
                <div class="list-block ">
                    <span class="bold">Ege University</span>
                    BS, Computer Engineering <br/>
                    <ol>
                        <li></li>
                        <li>
                            Thesis: Simulation of a Congestion Control Algorithm <br/>
                            Advisor: Prof. Dr. Levent Toker
                        </li>
                    </ol>
                    2003 -  2007
                </div>
                <div class="list-block ">
                    <span class="bold">Porto University</span>
                    Erasmus, Informatics and Computer Engineering <br/>
                    2005 - 2006
                </div>
            </div>
            <div class="awards">
                <div class="heading alert alert-info">
                    <i class="icon-trophy"></i> Honors and Awards </div>
                <div class="list-block">
                    <ol>
                        <li>Sabancı University MS. Full Scholarship, 2007-2009</li>
                        <li>TÜBİTAK MS. Scholarship, 2007-2009</li>
                    </ol>
                </div>
            </div>
            <div class="skillset">
                <div class="heading alert alert-info">
                    <i class="icon-wrench"></i> Skills & Expertise
                </div>
                <div class="list-block ">
                    <ol>
                        <li>
                            Java, Javascript, Groovy, PHP, C++, C#, Scala
                        </li>
                        <li>
                            Grails, Spring MVC, Zend Framework, JQuery, Qt, OMNET++
                        </li>
                        <li>
                            Git, Solr, Hibernate, Doctrine, RabbitMQ, Web Services
                        </li>
                        <li>
                            Design Patterns, OOP, Jenkins, TDD, MongoDB, PlantUML
                        </li>
                    </ol>
                </div>
            </div>
            <div class="interests">
                <div class="heading alert alert-info">
                    <i class="icon-music"></i> Interests </div>
                <div class="list-block">
                    <ol>
                        <li><g:link action="index" params="[mode:'fason']">Music</g:link></li>
                        <li>Snowboard</li>
                    </ol>
                </div>
            </div>
            <div class="social-links">
                <ul class="quicklinks">
                    <li><a href="<g:message code="contact.linkedin"/>" target="_blank"><i class="icon-linkedin-sign icon-large"></i></a></li>
                    <li><a href="<g:message code="contact.facebook"/>" target="_blank"><i class="icon-facebook-sign icon-large"></i></a></li>
                </ul>
            </div>
        </div>
    </div><!--/row-->

</div><!--/.fluid-container-->


<!-- contact model -->
<div id="contactModel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h3 id="myModalLabel"><i class="icon-envelope-alt"></i> Contact Can Yücel</h3>
    </div>
    <g:form action="post" controller="contact"  class="">
        <div class="modal-body">
            <input type="text" name="fullname" placeholder="Name"> <br/>
            <input type="text" name="email" placeholder="Email"> <br/>
            <textarea name="message" placeholder="Your Message"></textarea>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary pull-left">Send Email</button>
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/index/topBar.gsp
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <g:link class="brand" controller="index" action="change">
                <g:if test="${!fasonMode}">
                    <img src="${resource(dir: 'images', file: 'can-on-thefason.png')}" width="156" alt="Canthefason - Senior Software Engineer">
                </g:if>
                <g:else>
                    <img src="${resource(dir: 'images', file: 'canthefason-on.png')}" width="156" alt="cantheFason - Junior Musician">
                </g:else>
            </g:link>
            <a class="brand" href="index.html" style="display:none;"><img src="${resource(dir: 'images', file: 'canthefason-on.png')}" width="156" alt="Typica - Bootstrap Awesome Template!"></a>
            <div class="nav-collapse">
                <ul class="nav pull-right">
                    <li class="active"><g:link uri="/">Home</g:link></li>
                    <g:if test="${!fasonMode}">
                        <li><g:link action="resume">CV/Resume</g:link></li>
                    </g:if>
                    <g:else>
                        <li><g:link action="picture" controller="media">Gallery</g:link></li>
                        <li><g:link action="performance" controller="media">Performance</g:link></li>
                    </g:else>
                    <li><g:link controller="contact">Contact</g:link></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>